/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "b9e5b8a154549bb57a57b9c822607bc3289fc5b9"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
