/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "ab212df482c8fd5b1c1fb302717876d542549624"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
